# Generated by Django 3.2.12 on 2023-01-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'home_todo',
            },
        ),
    ]
